pages:
  image: node:latest
  stage: deploy
  script:
  - npm install -g redoc-cli
  - redoc-cli build -o public/index.html docs/web_deploy/openapi.yaml
  artifacts:
    paths:
    - public
  only:
  - main
